language: csharp
sudo: required

os:
  - linux
  - osx

mono:
  - weekly
  - latest
  - 4.8.0
  - 4.4.2

install:

script: 
  - ./fcs/build.sh Build

# Woes with doing more build/test on linux
#
# This fails because NUnit gives an exception (!!!!)
#  - ./fcs/build.sh Test.NetFx
# 
#
# This fails because Nuget packaging doesn't like backslashes in the package file, but Windows does
#  - ./fcs/build.sh NuGet

# Fails on Travis OSX too often because there are network outages on that configuration getting the Mono MDK
# Fails on Travis Linux with Mono latest do to a trust issue with certs on package restore?
matrix:
  exclude:
    - os: osx
      mono: 4.4.2
    - os: osx
      mono: 4.8.0
    - os: linux
      mono: latest

