language: csharp

os:
  - linux
  - osx

mono:
  - nightly
  - beta
  - latest
  - 4.8.1
  - 4.4.2

matrix:
  allow_failures:
    - mono: nightly
      os: osx

sudo: false

install:

script:
  - ./build.sh NuGet

# Fails on Travis OSX too often because there are network outages on that configuration getting the Mono MDK

# Fails on Travis Linux Mono latest and 4.8.0 because FSharp.Core 4.3.0.0 is not available, see
#   https://github.com/fsharp/fsharp/pull/689
#   https://github.com/mono/linux-packaging-fsharp/pull/3

#  matrix:
#    exclude:
#      - os: osx
#        mono: 4.4.2
#      - os: osx
#        mono: 4.8.0

#  allow_failures:
#    - os: osx
#      mono: latest
#    - os: linux
#      mono: latest
#    - os: linux
#      mono: 4.8.0
#    - os: osx
#      mono: latest
